version: '3.8'

services:
  solutions:
    build:
      context: ./
      target: runner
    container_name: solutions
    restart: unless-stopped
    networks:
      - solutions
    ports:
      - 3000:3000

networks:
  solutions:
