export const COUNTRY_CODES = [
  {
    name: 'Afghanistan',
    persian_name: 'افغانستان',
    dial_code: '+93',
    code: 'AF',
  },
  {
    name: 'Aland Islands',
    persian_name: 'جزایر آلند',
    dial_code: '+358',
    code: 'AX',
  },
  {
    name: 'Albania',
    persian_name: 'آلبانی',
    dial_code: '+355',
    code: 'AL',
  },
  {
    name: 'Algeria',
    persian_name: 'الجزایر',
    dial_code: '+213',
    code: 'DZ',
  },
  {
    name: 'AmericanSamoa',
    persian_name: 'ساموآی امریکایی',
    dial_code: '+1684',
    code: 'AS',
  },
  {
    name: 'Andorra',
    persian_name: 'آندورا',
    dial_code: '+376',
    code: 'AD',
  },
  {
    name: 'Angola',
    persian_name: 'آنگولا',
    dial_code: '+244',
    code: 'AO',
  },
  {
    name: 'Anguilla',
    persian_name: 'آنگوئیلا',
    dial_code: '+1264',
    code: 'AI',
  },
  {
    name: 'Antarctica',
    persian_name: 'جنوبگان',
    dial_code: '+672',
    code: 'AQ',
  },
  {
    name: 'Antigua and Barbuda',
    persian_name: 'آنتیگوا و باربودا',
    dial_code: '+1268',
    code: 'AG',
  },
  {
    name: 'Argentina',
    persian_name: 'آرژانتین',
    dial_code: '+54',
    code: 'AR',
  },
  {
    name: 'Armenia',
    persian_name: 'ارمنستان',
    dial_code: '+374',
    code: 'AM',
  },
  {
    name: 'Aruba',
    persian_name: 'آروبا',
    dial_code: '+297',
    code: 'AW',
  },
  {
    name: 'Australia',
    persian_name: 'استرالیا',
    dial_code: '+61',
    code: 'AU',
  },
  {
    name: 'Austria',
    persian_name: 'اتریش',
    dial_code: '+43',
    code: 'AT',
  },
  {
    name: 'Azerbaijan',
    persian_name: 'آذربایجان',
    dial_code: '+994',
    code: 'AZ',
  },
  {
    name: 'Bahamas',
    persian_name: 'باهاما',
    dial_code: '+1242',
    code: 'BS',
  },
  {
    name: 'Bahrain',
    persian_name: 'بحرین',
    dial_code: '+973',
    code: 'BH',
  },
  {
    name: 'Bangladesh',
    persian_name: 'بنگلادش',
    dial_code: '+880',
    code: 'BD',
  },
  {
    name: 'Barbados',
    persian_name: 'باربادوس',
    dial_code: '+1246',
    code: 'BB',
  },
  {
    name: 'Belarus',
    persian_name: 'بلاروس',
    dial_code: '+375',
    code: 'BY',
  },
  {
    name: 'Belgium',
    persian_name: 'بلژیک',
    dial_code: '+32',
    code: 'BE',
  },
  {
    name: 'Belize',
    persian_name: 'بلیز',
    dial_code: '+501',
    code: 'BZ',
  },
  {
    name: 'Benin',
    persian_name: 'بنین',
    dial_code: '+229',
    code: 'BJ',
  },
  {
    name: 'Bermuda',
    persian_name: 'برمودا',
    dial_code: '+1441',
    code: 'BM',
  },
  {
    name: 'Bhutan',
    persian_name: 'بوتان',
    dial_code: '+975',
    code: 'BT',
  },
  {
    name: 'Bolivia, Plurinational State of',
    persian_name: 'بولیوی',
    dial_code: '+591',
    code: 'BO',
  },
  {
    name: 'Bosnia and Herzegovina',
    persian_name: 'بوسنی و هرزگوین',
    dial_code: '+387',
    code: 'BA',
  },
  {
    name: 'Botswana',
    persian_name: 'بوتسوانا',
    dial_code: '+267',
    code: 'BW',
  },
  {
    name: 'Brazil',
    persian_name: 'برزیل',
    dial_code: '+55',
    code: 'BR',
  },
  {
    name: 'British Indian Ocean Territory',
    persian_name: 'قلمرو هندی اقیانوس هند بریتانیا',
    dial_code: '+246',
    code: 'IO',
  },
  {
    name: 'Brunei Darussalam',
    persian_name: 'برونئی',
    dial_code: '+673',
    code: 'BN',
  },
  {
    name: 'Bulgaria',
    persian_name: 'بلغارستان',
    dial_code: '+359',
    code: 'BG',
  },
  {
    name: 'Burkina Faso',
    persian_name: 'بورکینافاسو',
    dial_code: '+226',
    code: 'BF',
  },
  {
    name: 'Burundi',
    persian_name: 'بوروندی',
    dial_code: '+257',
    code: 'BI',
  },
  {
    name: 'Cambodia',
    persian_name: 'کامبوج',
    dial_code: '+855',
    code: 'KH',
  },
  {
    name: 'Cameroon',
    persian_name: 'کامرون',
    dial_code: '+237',
    code: 'CM',
  },
  {
    name: 'Canada',
    persian_name: 'کانادا',
    dial_code: '+1',
    code: 'CA',
  },
  {
    name: 'Cape Verde',
    persian_name: 'کیپ ورد',
    dial_code: '+238',
    code: 'CV',
  },
  {
    name: 'Cayman Islands',
    persian_name: 'جزایر کیمن',
    dial_code: '+ 345',
    code: 'KY',
  },
  {
    name: 'Central African Republic',
    persian_name: 'جمهوری آفریقای مرکزی',
    dial_code: '+236',
    code: 'CF',
  },
  {
    name: 'Chad',
    persian_name: 'چاد',
    dial_code: '+235',
    code: 'TD',
  },
  {
    name: 'Chile',
    persian_name: 'شیلی',
    dial_code: '+56',
    code: 'CL',
  },
  {
    name: 'China',
    persian_name: 'چین',
    dial_code: '+86',
    code: 'CN',
  },
  {
    name: 'Christmas Island',
    persian_name: 'جزیره کریسمس',
    dial_code: '+61',
    code: 'CX',
  },
  {
    name: 'Cocos (Keeling) Islands',
    persian_name: 'جزایر کوکوس (کیلینگ)',
    dial_code: '+61',
    code: 'CC',
  },
  {
    name: 'Colombia',
    persian_name: 'کلمبیا',
    dial_code: '+57',
    code: 'CO',
  },
  {
    name: 'Comoros',
    persian_name: 'کومور',
    dial_code: '+269',
    code: 'KM',
  },
  {
    name: 'Congo',
    persian_name: 'کنگو',
    dial_code: '+242',
    code: 'CG',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    persian_name: 'جمهوری دموکراتیک کنگو',
    dial_code: '+243',
    code: 'CD',
  },
  {
    name: 'Cook Islands',
    persian_name: 'جزایر کوک',
    dial_code: '+682',
    code: 'CK',
  },
  {
    name: 'Costa Rica',
    persian_name: 'کاستاریکا',
    dial_code: '+506',
    code: 'CR',
  },
  {
    name: "Cote d'Ivoire",
    persian_name: 'ساحل عاج',
    dial_code: '+225',
    code: 'CI',
  },
  {
    name: 'Croatia',
    persian_name: 'کرواسی',
    dial_code: '+385',
    code: 'HR',
  },
  {
    name: 'Cuba',
    persian_name: 'کوبا',
    dial_code: '+53',
    code: 'CU',
  },
  {
    name: 'Cyprus',
    persian_name: 'قبرس',
    dial_code: '+357',
    code: 'CY',
  },
  {
    name: 'Czech Republic',
    persian_name: 'جمهوری چک',
    dial_code: '+420',
    code: 'CZ',
  },
  {
    name: 'Denmark',
    persian_name: 'دانمارک',
    dial_code: '+45',
    code: 'DK',
  },
  {
    name: 'Djibouti',
    persian_name: 'جیبوتی',
    dial_code: '+253',
    code: 'DJ',
  },
  {
    name: 'Dominica',
    persian_name: 'دومینیکا',
    dial_code: '+1767',
    code: 'DM',
  },
  {
    name: 'Dominican Republic',
    persian_name: 'جمهوری دومینیکن',
    dial_code: '+1849',
    code: 'DO',
  },
  {
    name: 'Ecuador',
    persian_name: 'اکوادور',
    dial_code: '+593',
    code: 'EC',
  },
  {
    name: 'Egypt',
    persian_name: 'مصر',
    dial_code: '+20',
    code: 'EG',
  },
  {
    name: 'El Salvador',
    persian_name: 'السالوادور',
    dial_code: '+503',
    code: 'SV',
  },
  {
    name: 'Equatorial Guinea',
    persian_name: 'گینه استوایی',
    dial_code: '+240',
    code: 'GQ',
  },
  {
    name: 'Eritrea',
    persian_name: 'اریتره',
    dial_code: '+291',
    code: 'ER',
  },
  {
    name: 'Estonia',
    persian_name: 'استونی',
    dial_code: '+372',
    code: 'EE',
  },
  {
    name: 'Ethiopia',
    persian_name: 'اتیوپی',
    dial_code: '+251',
    code: 'ET',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    persian_name: 'جزایر فالکلند (مالویناس)',
    dial_code: '+500',
    code: 'FK',
  },
  {
    name: 'Faroe Islands',
    persian_name: 'جزایر فارو',
    dial_code: '+298',
    code: 'FO',
  },
  {
    name: 'Fiji',
    persian_name: 'فیجی',
    dial_code: '+679',
    code: 'FJ',
  },
  {
    name: 'Finland',
    persian_name: 'فنلاند',
    dial_code: '+358',
    code: 'FI',
  },
  {
    name: 'France',
    persian_name: 'فرانسه',
    dial_code: '+33',
    code: 'FR',
  },
  {
    name: 'French Guiana',
    persian_name: 'گویان فرانسه',
    dial_code: '+594',
    code: 'GF',
  },
  {
    name: 'French Polynesia',
    persian_name: 'پلی‌نزی فرانسه',
    dial_code: '+689',
    code: 'PF',
  },
  {
    name: 'Gabon',
    persian_name: 'گابن',
    dial_code: '+241',
    code: 'GA',
  },
  {
    name: 'Gambia',
    persian_name: 'گامبیا',
    dial_code: '+220',
    code: 'GM',
  },
  {
    name: 'Georgia',
    persian_name: 'گرجستان',
    dial_code: '+995',
    code: 'GE',
  },
  {
    name: 'Germany',
    persian_name: 'آلمان',
    dial_code: '+49',
    code: 'DE',
  },
  {
    name: 'Ghana',
    persian_name: 'غنا',
    dial_code: '+233',
    code: 'GH',
  },
  {
    name: 'Gibraltar',
    persian_name: 'جبل‌طارق',
    dial_code: '+350',
    code: 'GI',
  },
  {
    name: 'Greece',
    persian_name: 'یونان',
    dial_code: '+30',
    code: 'GR',
  },
  {
    name: 'Greenland',
    persian_name: 'گرینلند',
    dial_code: '+299',
    code: 'GL',
  },
  {
    name: 'Grenada',
    persian_name: 'گرنادا',
    dial_code: '+1473',
    code: 'GD',
  },
  {
    name: 'Guadeloupe',
    persian_name: 'گوادلوپ',
    dial_code: '+590',
    code: 'GP',
  },
  {
    name: 'Guam',
    persian_name: 'گوام',
    dial_code: '+1671',
    code: 'GU',
  },
  {
    name: 'Guatemala',
    persian_name: 'گواتمالا',
    dial_code: '+502',
    code: 'GT',
  },
  {
    name: 'Guernsey',
    persian_name: 'گرنزی',
    dial_code: '+44',
    code: 'GG',
  },
  {
    name: 'Guinea',
    persian_name: 'گینه',
    dial_code: '+224',
    code: 'GN',
  },
  {
    name: 'Guinea-Bissau',
    persian_name: 'گینه بیسائو',
    dial_code: '+245',
    code: 'GW',
  },
  {
    name: 'Guyana',
    persian_name: 'گویان',
    dial_code: '+592',
    code: 'GY',
  },
  {
    name: 'Haiti',
    persian_name: 'هائیتی',
    dial_code: '+509',
    code: 'HT',
  },
  {
    name: 'Holy See (Vatican City State)',
    persian_name: 'واتیکان',
    dial_code: '+379',
    code: 'VA',
  },
  {
    name: 'Honduras',
    persian_name: 'هندوراس',
    dial_code: '+504',
    code: 'HN',
  },
  {
    name: 'Hong Kong',
    persian_name: 'هنگ کنگ',
    dial_code: '+852',
    code: 'HK',
  },
  {
    name: 'Hungary',
    persian_name: 'مجارستان',
    dial_code: '+36',
    code: 'HU',
  },
  {
    name: 'Iceland',
    persian_name: 'ایسلند',
    dial_code: '+354',
    code: 'IS',
  },
  {
    name: 'India',
    persian_name: 'هند',
    dial_code: '+91',
    code: 'IN',
  },
  {
    name: 'Indonesia',
    persian_name: 'اندونزی',
    dial_code: '+62',
    code: 'ID',
  },
  {
    name: 'Iran',
    persian_name: 'ایران',
    dial_code: '+98',
    code: 'IR',
  },
  {
    name: 'Iraq',
    persian_name: 'عراق',
    dial_code: '+964',
    code: 'IQ',
  },
  {
    name: 'Ireland',
    persian_name: 'ایرلند',
    dial_code: '+353',
    code: 'IE',
  },
  {
    name: 'Isle of Man',
    persian_name: 'جزیره من',
    dial_code: '+44',
    code: 'IM',
  },
  {
    name: 'Israel',
    persian_name: 'اسرائیل',
    dial_code: '+972',
    code: 'IL',
  },
  {
    name: 'Italy',
    persian_name: 'ایتالیا',
    dial_code: '+39',
    code: 'IT',
  },
  {
    name: 'Jamaica',
    persian_name: 'جامائیکا',
    dial_code: '+1876',
    code: 'JM',
  },
  {
    name: 'Japan',
    persian_name: 'ژاپن',
    dial_code: '+81',
    code: 'JP',
  },
  {
    name: 'Jersey',
    persian_name: 'جرزی',
    dial_code: '+44',
    code: 'JE',
  },
  {
    name: 'Jordan',
    persian_name: 'اردن',
    dial_code: '+962',
    code: 'JO',
  },
  {
    name: 'Kazakhstan',
    persian_name: 'قزاقستان',
    dial_code: '+7',
    code: 'KZ',
  },
  {
    name: 'Kenya',
    persian_name: 'کنیا',
    dial_code: '+254',
    code: 'KE',
  },
  {
    name: 'Kiribati',
    persian_name: 'کیریباتی',
    dial_code: '+686',
    code: 'KI',
  },
  {
    name: "Korea, Democratic People's Republic of",
    persian_name: 'کره شمالی',
    dial_code: '+850',
    code: 'KP',
  },
  {
    name: 'Korea, Republic of',
    persian_name: 'کره جنوبی',
    dial_code: '+82',
    code: 'KR',
  },
  {
    name: 'Kuwait',
    persian_name: 'کویت',
    dial_code: '+965',
    code: 'KW',
  },
  {
    name: 'Kyrgyzstan',
    persian_name: 'قرقیزستان',
    dial_code: '+996',
    code: 'KG',
  },
  {
    name: "Lao People's Democratic Republic",
    persian_name: 'لائوس',
    dial_code: '+856',
    code: 'LA',
  },
  {
    name: 'Latvia',
    persian_name: 'لتونی',
    dial_code: '+371',
    code: 'LV',
  },
  {
    name: 'Lebanon',
    persian_name: 'لبنان',
    dial_code: '+961',
    code: 'LB',
  },
  {
    name: 'Lesotho',
    persian_name: 'لسوتو',
    dial_code: '+266',
    code: 'LS',
  },
  {
    name: 'Liberia',
    persian_name: 'لیبریا',
    dial_code: '+231',
    code: 'LR',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    persian_name: 'لیبی',
    dial_code: '+218',
    code: 'LY',
  },
  {
    name: 'Liechtenstein',
    persian_name: 'لیختن‌اشتاین',
    dial_code: '+423',
    code: 'LI',
  },
  {
    name: 'Lithuania',
    persian_name: 'لیتوانی',
    dial_code: '+370',
    code: 'LT',
  },
  {
    name: 'Luxembourg',
    persian_name: 'لوکزامبورگ',
    dial_code: '+352',
    code: 'LU',
  },
  {
    name: 'Macao',
    persian_name: 'ماکائو',
    dial_code: '+853',
    code: 'MO',
  },
  {
    name: 'Macedonia',
    persian_name: 'مقدونیه',
    dial_code: '+389',
    code: 'MK',
  },
  {
    name: 'Madagascar',
    persian_name: 'ماداگاسکار',
    dial_code: '+261',
    code: 'MG',
  },
  {
    name: 'Malawi',
    persian_name: 'مالاوی',
    dial_code: '+265',
    code: 'MW',
  },
  {
    name: 'Malaysia',
    persian_name: 'مالزی',
    dial_code: '+60',
    code: 'MY',
  },
  {
    name: 'Maldives',
    persian_name: 'مالدیو',
    dial_code: '+960',
    code: 'MV',
  },
  {
    name: 'Mali',
    persian_name: 'مالی',
    dial_code: '+223',
    code: 'ML',
  },
  {
    name: 'Malta',
    persian_name: 'مالت',
    dial_code: '+356',
    code: 'MT',
  },
  {
    name: 'Marshall Islands',
    persian_name: 'جزایر مارشال',
    dial_code: '+692',
    code: 'MH',
  },
  {
    name: 'Martinique',
    persian_name: 'مارتینیک',
    dial_code: '+596',
    code: 'MQ',
  },
  {
    name: 'Mauritania',
    persian_name: 'موریتانی',
    dial_code: '+222',
    code: 'MR',
  },
  {
    name: 'Mauritius',
    persian_name: 'موریس',
    dial_code: '+230',
    code: 'MU',
  },
  {
    name: 'Mayotte',
    persian_name: 'مایوت',
    dial_code: '+262',
    code: 'YT',
  },
  {
    name: 'Mexico',
    persian_name: 'مکزیک',
    dial_code: '+52',
    code: 'MX',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    persian_name: 'میکرونزی',
    dial_code: '+691',
    code: 'FM',
  },
  {
    name: 'Moldova',
    persian_name: 'مولداوی',
    dial_code: '+373',
    code: 'MD',
  },
  {
    name: 'Monaco',
    persian_name: 'موناکو',
    dial_code: '+377',
    code: 'MC',
  },
  {
    name: 'Mongolia',
    persian_name: 'مغولستان',
    dial_code: '+976',
    code: 'MN',
  },
  {
    name: 'Montenegro',
    persian_name: 'مونته‌نگرو',
    dial_code: '+382',
    code: 'ME',
  },
  {
    name: 'Montserrat',
    persian_name: 'مونت‌سرات',
    dial_code: '+1664',
    code: 'MS',
  },
  {
    name: 'Morocco',
    persian_name: 'مراکش',
    dial_code: '+212',
    code: 'MA',
  },
  {
    name: 'Mozambique',
    persian_name: 'موزامبیک',
    dial_code: '+258',
    code: 'MZ',
  },
  {
    name: 'Myanmar',
    persian_name: 'میانمار',
    dial_code: '+95',
    code: 'MM',
  },
  {
    name: 'Namibia',
    persian_name: 'نامیبیا',
    dial_code: '+264',
    code: 'NA',
  },
  {
    name: 'Nauru',
    persian_name: 'نائورو',
    dial_code: '+674',
    code: 'NR',
  },
  {
    name: 'Nepal',
    persian_name: 'نپال',
    dial_code: '+977',
    code: 'NP',
  },
  {
    name: 'Netherlands',
    persian_name: 'هلند',
    dial_code: '+31',
    code: 'NL',
  },
  {
    name: 'Netherlands Antilles',
    persian_name: 'جزایر آنتیل هلند',
    dial_code: '+599',
    code: 'AN',
  },
  {
    name: 'New Caledonia',
    persian_name: 'کالدونیای جدید',
    dial_code: '+687',
    code: 'NC',
  },
  {
    name: 'New Zealand',
    persian_name: 'نیوزیلند',
    dial_code: '+64',
    code: 'NZ',
  },
  {
    name: 'Nicaragua',
    persian_name: 'نیکاراگوئه',
    dial_code: '+505',
    code: 'NI',
  },
  {
    name: 'Niger',
    persian_name: 'نیجر',
    dial_code: '+227',
    code: 'NE',
  },
  {
    name: 'Nigeria',
    persian_name: 'نیجریه',
    dial_code: '+234',
    code: 'NG',
  },
  {
    name: 'Niue',
    persian_name: 'نیوئه',
    dial_code: '+683',
    code: 'NU',
  },
  {
    name: 'Norfolk Island',
    persian_name: 'جزیره نورفک',
    dial_code: '+672',
    code: 'NF',
  },
  {
    name: 'Northern Mariana Islands',
    persian_name: 'جزایر ماریانای شمالی',
    dial_code: '+1670',
    code: 'MP',
  },
  {
    name: 'Norway',
    persian_name: 'نروژ',
    dial_code: '+47',
    code: 'NO',
  },
  {
    name: 'Oman',
    persian_name: 'عمان',
    dial_code: '+968',
    code: 'OM',
  },
  {
    name: 'Pakistan',
    persian_name: 'پاکستان',
    dial_code: '+92',
    code: 'PK',
  },
  {
    name: 'Palau',
    persian_name: 'پالائو',
    dial_code: '+680',
    code: 'PW',
  },
  {
    name: 'Palestine',
    persian_name: 'فلسطین',
    dial_code: '+970',
    code: 'PS',
  },
  {
    name: 'Panama',
    persian_name: 'پاناما',
    dial_code: '+507',
    code: 'PA',
  },
  {
    name: 'Papua New Guinea',
    persian_name: 'پاپوا گینه نو',
    dial_code: '+675',
    code: 'PG',
  },
  {
    name: 'Paraguay',
    persian_name: 'پاراگوئه',
    dial_code: '+595',
    code: 'PY',
  },
  {
    name: 'Peru',
    persian_name: 'پرو',
    dial_code: '+51',
    code: 'PE',
  },
  {
    name: 'Philippines',
    persian_name: 'فیلیپین',
    dial_code: '+63',
    code: 'PH',
  },
  {
    name: 'Pitcairn',
    persian_name: 'پیتکرن',
    dial_code: '+872',
    code: 'PN',
  },
  {
    name: 'Poland',
    persian_name: 'لهستان',
    dial_code: '+48',
    code: 'PL',
  },
  {
    name: 'Portugal',
    persian_name: 'پرتغال',
    dial_code: '+351',
    code: 'PT',
  },
  {
    name: 'Puerto Rico',
    persian_name: 'پورتوریکو',
    dial_code: '+1939',
    code: 'PR',
  },
  {
    name: 'Qatar',
    persian_name: 'قطر',
    dial_code: '+974',
    code: 'QA',
  },
  {
    name: 'Romania',
    persian_name: 'رومانی',
    dial_code: '+40',
    code: 'RO',
  },
  {
    name: 'Russia',
    persian_name: 'روسیه',
    dial_code: '+7',
    code: 'RU',
  },
  {
    name: 'Rwanda',
    persian_name: 'رواندا',
    dial_code: '+250',
    code: 'RW',
  },
  {
    name: 'Réunion',
    persian_name: 'ریونیون',
    dial_code: '+262',
    code: 'RE',
  },
  {
    name: 'Saint Barthélemy',
    persian_name: 'سن بارتلمی',
    dial_code: '+590',
    code: 'BL',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    persian_name: 'سنت هلنا',
    dial_code: '+290',
    code: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    persian_name: 'سنت کیتس و نویس',
    dial_code: '+1869',
    code: 'KN',
  },
  {
    name: 'Saint Lucia',
    persian_name: 'سنت لوسیا',
    dial_code: '+1758',
    code: 'LC',
  },
  {
    name: 'Saint Martin',
    persian_name: 'سنت مارتین',
    dial_code: '+590',
    code: 'MF',
  },
  {
    name: 'Saint Pierre and Miquelon',
    persian_name: 'سنت پیر و میکلن',
    dial_code: '+508',
    code: 'PM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    persian_name: 'سنت وینسنت و گرنادین',
    dial_code: '+1784',
    code: 'VC',
  },
  {
    name: 'Samoa',
    persian_name: 'ساموآ',
    dial_code: '+685',
    code: 'WS',
  },
  {
    name: 'San Marino',
    persian_name: 'سان‌مارینو',
    dial_code: '+378',
    code: 'SM',
  },
  {
    name: 'Sao Tome and Principe',
    persian_name: 'سائوتومه و پرنسیپ',
    dial_code: '+239',
    code: 'ST',
  },
  {
    name: 'Saudi Arabia',
    persian_name: 'عربستان سعودی',
    dial_code: '+966',
    code: 'SA',
  },
  {
    name: 'Senegal',
    persian_name: 'سنگال',
    dial_code: '+221',
    code: 'SN',
  },
  {
    name: 'Serbia',
    persian_name: 'صربستان',
    dial_code: '+381',
    code: 'RS',
  },
  {
    name: 'Seychelles',
    persian_name: 'سیشل',
    dial_code: '+248',
    code: 'SC',
  },
  {
    name: 'Sierra Leone',
    persian_name: 'سیرالئون',
    dial_code: '+232',
    code: 'SL',
  },
  {
    name: 'Singapore',
    persian_name: 'سنگاپور',
    dial_code: '+65',
    code: 'SG',
  },
  {
    name: 'Slovakia',
    persian_name: 'اسلواکی',
    dial_code: '+421',
    code: 'SK',
  },
  {
    name: 'Slovenia',
    persian_name: 'اسلوونی',
    dial_code: '+386',
    code: 'SI',
  },
  {
    name: 'Solomon Islands',
    persian_name: 'جزایر سلیمان',
    dial_code: '+677',
    code: 'SB',
  },
  {
    name: 'Somalia',
    persian_name: 'سومالی',
    dial_code: '+252',
    code: 'SO',
  },
  {
    name: 'South Africa',
    persian_name: 'آفریقای جنوبی',
    dial_code: '+27',
    code: 'ZA',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    persian_name: 'جزایر جورجیای جنوبی و ساندویچ جنوبی',
    dial_code: '+500',
    code: 'GS',
  },
  {
    name: 'Spain',
    persian_name: 'اسپانیا',
    dial_code: '+34',
    code: 'ES',
  },
  {
    name: 'Sri Lanka',
    persian_name: 'سریلانکا',
    dial_code: '+94',
    code: 'LK',
  },
  {
    name: 'Sudan',
    persian_name: 'سودان',
    dial_code: '+249',
    code: 'SD',
  },
  {
    name: 'Suriname',
    persian_name: 'سورینام',
    dial_code: '+597',
    code: 'SR',
  },
  {
    name: 'Svalbard and Jan Mayen',
    persian_name: 'سوالبارد و یان ماین',
    dial_code: '+47',
    code: 'SJ',
  },
  {
    name: 'Swaziland',
    persian_name: 'سوازیلند',
    dial_code: '+268',
    code: 'SZ',
  },
  {
    name: 'Sweden',
    persian_name: 'سوئد',
    dial_code: '+46',
    code: 'SE',
  },
  {
    name: 'Switzerland',
    persian_name: 'سوئیس',
    dial_code: '+41',
    code: 'CH',
  },
  {
    name: 'Syrian Arab Republic',
    persian_name: 'سوریه',
    dial_code: '+963',
    code: 'SY',
  },
  {
    name: 'Taiwan',
    persian_name: 'تایوان',
    dial_code: '+886',
    code: 'TW',
  },
  {
    name: 'Tajikistan',
    persian_name: 'تاجیکستان',
    dial_code: '+992',
    code: 'TJ',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    persian_name: 'تانزانیا',
    dial_code: '+255',
    code: 'TZ',
  },
  {
    name: 'Thailand',
    persian_name: 'تایلند',
    dial_code: '+66',
    code: 'TH',
  },
  {
    name: 'Timor-Leste',
    persian_name: 'تیمور شرقی',
    dial_code: '+670',
    code: 'TL',
  },
  {
    name: 'Togo',
    persian_name: 'توگو',
    dial_code: '+228',
    code: 'TG',
  },
  {
    name: 'Tokelau',
    persian_name: 'توکلائو',
    dial_code: '+690',
    code: 'TK',
  },
  {
    name: 'Tonga',
    persian_name: 'تونگا',
    dial_code: '+676',
    code: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    persian_name: 'ترینیداد و توباگو',
    dial_code: '+1868',
    code: 'TT',
  },
  {
    name: 'Tunisia',
    persian_name: 'تونس',
    dial_code: '+216',
    code: 'TN',
  },
  {
    name: 'Turkey',
    persian_name: 'ترکیه',
    dial_code: '+90',
    code: 'TR',
  },
  {
    name: 'Turkmenistan',
    persian_name: 'ترکمنستان',
    dial_code: '+993',
    code: 'TM',
  },
  {
    name: 'Turks and Caicos Islands',
    persian_name: 'جزایر تورکس و کایکوس',
    dial_code: '+1649',
    code: 'TC',
  },
  {
    name: 'Tuvalu',
    persian_name: 'تووالو',
    dial_code: '+688',
    code: 'TV',
  },
  {
    name: 'Uganda',
    persian_name: 'اوگاندا',
    dial_code: '+256',
    code: 'UG',
  },
  {
    name: 'Ukraine',
    persian_name: 'اوکراین',
    dial_code: '+380',
    code: 'UA',
  },
  {
    name: 'United Arab Emirates',
    persian_name: 'امارات متحده عربی',
    dial_code: '+971',
    code: 'AE',
  },
  {
    name: 'United Kingdom',
    persian_name: 'بریتانیا',
    dial_code: '+44',
    code: 'GB',
  },
  {
    name: 'United States',
    persian_name: 'ایالات متحده آمریکا',
    dial_code: '+1',
    code: 'US',
  },
  {
    name: 'Uruguay',
    persian_name: 'اروگوئه',
    dial_code: '+598',
    code: 'UY',
  },
  {
    name: 'Uzbekistan',
    persian_name: 'ازبکستان',
    dial_code: '+998',
    code: 'UZ',
  },
  {
    name: 'Vanuatu',
    persian_name: 'وانواتو',
    dial_code: '+678',
    code: 'VU',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    persian_name: 'ونزوئلا',
    dial_code: '+58',
    code: 'VE',
  },
  {
    name: 'Vietnam',
    dial_code: '+84',
    persian_name: 'ویتنام',
    code: 'VN',
  },
  {
    name: 'Virgin Islands, British',
    persian_name: 'جزایر ویرجین بریتانیا',
    dial_code: '+1284',
    code: 'VG',
  },
  {
    name: 'Virgin Islands, U.S.',
    persian_name: 'جزایر ویرجین آمریکا',
    dial_code: '+1340',
    code: 'VI',
  },
  {
    name: 'Wallis and Futuna',
    persian_name: 'والیس و فوتونا',
    dial_code: '+681',
    code: 'WF',
  },
  {
    name: 'Yemen',
    dial_code: '+967',
    persian_name: 'یمن',
    code: 'YE',
  },
  {
    name: 'Zambia',
    dial_code: '+260',
    persian_name: 'زامبیا',
    code: 'ZM',
  },
  {
    name: 'Zimbabwe',
    dial_code: '+263',
    persian_name: 'زیمبابوه',
    code: 'ZW',
  },
]

export const COUNTRY_LABELED = COUNTRY_CODES.map(country => ({
  ...country,
  label: country.persian_name,
  value: country.persian_name,
}))
