export const SOCIAL_NETWORKS = [
  { en: 'Facebook', fa: 'فیس‌بوک' },
  { en: 'Instagram', fa: 'اینستاگرام' },
  { en: 'Twitter', fa: 'توییتر' },
  { en: 'LinkedIn', fa: 'لینکداین' },
  { en: 'YouTube', fa: 'یوتیوب' },
  { en: 'Snapchat', fa: 'اسنپ‌چت' },
  { en: 'WhatsApp', fa: 'واتس‌اپ' },
  { en: 'Pinterest', fa: 'پین‌ترست' },
  { en: 'Reddit', fa: 'ردیت' },
  { en: 'TikTok', fa: 'تیک‌تاک' },
  { en: 'StackOverflow', fa: 'استک‌اورفلو' },
  { en: 'Github', fa: 'گیت‌هاب' },
  { en: 'Gitlab', fa: 'گیت‌لب' },
  { en: 'Bitbucket', fa: 'بیت‌باکت' },
  { en: 'Codepen', fa: 'کدپن' },
  { en: 'CodeSandbox', fa: 'کدسندباکس' },
  { en: 'Dribbble', fa: 'دریبل' },
  { en: 'Behance', fa: 'Behance' },
  { en: 'Medium', fa: 'مدیم' },
  { en: 'Dev.to', fa: 'دولوپر تو' },
  { en: 'Figma', fa: 'فیگما' },
]
