import {
  IconAdjustmentsStar,
  IconArrowsMaximize,
  IconBook,
  IconBooks,
  IconBrandBlogger,
  IconBrandGoogle,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandSlack,
  IconBrandX,
  IconBrandYoutube,
  IconBulb,
  IconCalculator,
  IconCertificate,
  IconConfetti,
  IconDeviceLaptop,
  IconHash,
  IconHeading,
  IconMailBolt,
  IconMessageStar,
  IconPaperclip,
  IconPencilHeart,
  IconQuestionMark,
  IconSeo,
  IconSpeakerphone,
  IconTextCaption,
  IconTopologyStar3,
  IconWorld,
} from '@tabler/icons-react'
import { ReactNode } from 'react'

export const CATEGORY_ICONS: Record<string, ReactNode> = {
  creative: <IconBulb className="w-6 h-6" />,
  copywriting: <IconBooks className="w-6 h-6" />,
  'branding-ads': <IconSpeakerphone className="w-6 h-6" />,
  'website-copy': <IconDeviceLaptop className="w-6 h-6" />,
  'social-media': <IconBrandSlack className="w-6 h-6" />,
  'business-shortcuts': <IconCertificate className="w-6 h-6" />,
}

export const SUB_CATEGORY_ICONS: Record<string, ReactNode> = {
  'google-ads': <IconBrandGoogle className="w-6 h-6" />,
  'instagram-caption': <IconBrandInstagram className="w-6 h-6" />,
  'youtube-title-idea': <IconBrandYoutube className="w-6 h-6" />,
  tweets: <IconBrandX className="w-6 h-6" />,
  'aida-framework': <IconTextCaption className="w-6 h-6" />,
  'pas-framework': <IconTopologyStar3 className="w-6 h-6" />,
  'post-blog': <IconBrandBlogger className="w-6 h-6" />,
  'seo-keywords': <IconSeo className="w-6 h-6" />,
  'title-generator': <IconHeading className="w-6 h-6" />,
  'linkedin-post': <IconBrandLinkedin className="w-6 h-6" />,
  'review-responder': <IconMessageStar className="w-6 h-6" />,
  'hashtag-generator': <IconHash className="w-6 h-6" />,
  'story-creator': <IconPencilHeart className="w-6 h-6" />,
  'content-expandor': <IconArrowsMaximize className="w-6 h-6" />,
  email: <IconMailBolt className="w-6 h-6" />,
  'question-answer': <IconQuestionMark className="w-6 h-6" />,
  'startup-ideas': <IconAdjustmentsStar className="w-6 h-6" />,
  'festivity-letters': <IconConfetti className="w-6 h-6" />,
  physics: <IconCalculator className="w-6 h-6" />,
}
